"""initial migration

Revision ID: 1234567890ab
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1234567890ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create product_categories table
    op.create_table('product_categories',
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_category_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)

    # Create products table
    op.create_table('products',
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)

    # Create product_attributes table
    op.create_table('product_attributes',
    sa.Column('attribute_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('attribute_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)

    # Create inventory_locations table
    op.create_table('inventory_locations',
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('capacity_units', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )

    # Create inventory_levels table
    op.create_table('inventory_levels',
    sa.Column('inventory_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), sa.Computed('quantity_on_hand - quantity_allocated'), nullable=False),
    sa.Column('quantity_on_order', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('last_counted', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('product_id', 'location_id')
    )
    op.create_index(op.f('ix_inventory_levels_product_id_location_id'), 'inventory_levels', ['product_id', 'location_id'], unique=False)

    # Create inventory_transactions table
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recorded_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_location_id'), 'inventory_transactions', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_date'), 'inventory_transactions', ['transaction_date'], unique=False)

    # Create demand_forecasts table
    op.create_table('demand_forecasts',
    sa.Column('forecast_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('predicted_demand', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('confidence_lower', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('confidence_upper', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('actual_demand', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('forecast_error', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    sa.UniqueConstraint('product_id', 'location_id', 'forecast_date', 'forecast_horizon')
    )
    op.create_index(op.f('ix_demand_forecasts_product_id_location_id_forecast_date'), 'demand_forecasts', ['product_id', 'location_id', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_demand_forecasts_model_used'), 'demand_forecasts', ['model_used'], unique=False)

    # Create forecast_models table
    op.create_table('forecast_models',
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('training_start_date', sa.Date(), nullable=True),
    sa.Column('training_end_date', sa.Date(), nullable=True),
    sa.Column('validation_start_date', sa.Date(), nullable=True),
    sa.Column('validation_end_date', sa.Date(), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )

    # Create forecast_features table
    op.create_table('forecast_features',
    sa.Column('feature_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('forecast_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('feature_type', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['demand_forecasts.forecast_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index(op.f('ix_forecast_features_forecast_id'), 'forecast_features', ['forecast_id'], unique=False)

    # Create sales_transactions table
    op.create_table('sales_transactions',
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('promotion_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.promotion_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_sales_transactions_product_id_transaction_date'), 'sales_transactions', ['product_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_sales_transactions_location_id_transaction_date'), 'sales_transactions', ['location_id', 'transaction_date'], unique=False)

    # Create demand_history table (will be converted to hypertable)
    op.create_table('demand_history',
    sa.Column('demand_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('demand_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('demand_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_promotion', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('demand_id')
    )
    op.create_index(op.f('ix_demand_history_product_id_date'), 'demand_history', ['product_id', 'date'], unique=False)
    op.create_index(op.f('ix_demand_history_location_id_date'), 'demand_history', ['location_id', 'date'], unique=False)

    # Create promotions table
    op.create_table('promotions',
    sa.Column('promotion_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promotion_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('total_uses_limit', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), server_default='0', nullable=True),
    sa.Column('target_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_index(op.f('ix_promotions_start_date_end_date'), 'promotions', ['start_date', 'end_date'], unique=False)

    # Create price_history table
    op.create_table('price_history',
    sa.Column('price_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=True),
    sa.Column('promotion_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.promotion_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_index(op.f('ix_price_history_product_id_effective_date'), 'price_history', ['product_id', 'effective_date'], unique=False)

    # Create suppliers table
    op.create_table('suppliers',
    sa.Column('supplier_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_code')
    )

    # Create purchase_orders table
    op.create_table('purchase_orders',
    sa.Column('po_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('po_id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)

    # Create purchase_order_items table
    op.create_table('purchase_order_items',
    sa.Column('po_item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('po_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), server_default='0', nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('po_item_id')
    )
    op.create_index(op.f('ix_purchase_order_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)

    # Create supplier_performance table
    op.create_table('supplier_performance',
    sa.Column('performance_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('supplier_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('evaluation_period_start', sa.Date(), nullable=False),
    sa.Column('evaluation_period_end', sa.Date(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_defect_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('average_lead_time', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('performance_id')
    )

    # Create users table
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    # Create data_ingestion_log table
    op.create_table('data_ingestion_log',
    sa.Column('log_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_data_ingestion_log_source_type'), 'data_ingestion_log', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_ingestion_log_status'), 'data_ingestion_log', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables in reverse order to avoid foreign key constraints
    op.drop_table('data_ingestion_log')
    op.drop_table('users')
    op.drop_table('supplier_performance')
    op.drop_table('purchase_order_items')
    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    op.drop_table('price_history')
    op.drop_table('promotions')
    op.drop_table('demand_history')
    op.drop_table('sales_transactions')
    op.drop_table('forecast_features')
    op.drop_table('forecast_models')
    op.drop_table('demand_forecasts')
    op.drop_table('inventory_transactions')
    op.drop_table('inventory_levels')
    op.drop_table('inventory_locations')
    op.drop_table('product_attributes')
    op.drop_table('products')
    op.drop_table('product_categories')
    # ### end Alembic commands ###